name: Release python package

on:
  push:
    branches:
      - main
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  REPOSITORY_USERNAME: __token__
  REPOSITORY_PASSWORD: ${{ secrets.PYPI_TOKEN }}


# .github/workflows/ci-cd.yml
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/<your-pypi-project-name>
    permissions:
      id-token: write
    steps:

      - name: Run Black Linter
        run: make check-format

      - name: Run Pytest
        run: make test

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Python Semantic Release
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github-Actions"
          semantic-release publish --post
