site_name: "datarails Documentation"

plugins:
  - mkdocstrings:
      handlers:
        python:
          show_source: false
  - search:
      lang: en

theme:
  name: "material"
  features:
    - content.code.copy

nav:
  - DataRailsStep: step.md
  - StepRunner: runner.md
  - DataBox: databox.md
  - DataRailsContext: context.md
