name: Release python package

on:
  push:
    branches:
      - main

# .github/workflows/ci-cd.yml
jobs:
  build_release:
    name: Increment Release Version and Run QA
    runs-on: ubuntu-latest
    steps:
      # retrieve your distributions here
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.5'

      - name: Make Development Environment
        run: make venv

      - name: Install Development Dependencies
        run: make install-dev

      - name: Run Tests
        run: make test

      - name: Check Formatting
        run: make check-format

      - name: Check Import Sorting
        run: make check-sort-imports

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

        # This is required to make sure that the git tag is created
      - name: Increment Version
        run: make release

      - name: Push Version Bump
        run: git push

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: build_release
    environment:
      name: release
      url: https://pypi.org/p/datarails
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.5'

      - name: Build Package
        run: python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
