name: Release python package

on:
  push:
    branches:
      - main

# .github/workflows/ci-cd.yml
jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      # retrieve your distributions here
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.5'

      - name: Make Development Environment
        run: make venv

      - name: Install Development Dependencies
        run: make install-dev

      - name: Run Tests
        run: make test

      - name: Check Formatting
        run: make check-format

      - name: Check Import Sorting
        run: make check-sort-imports

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

        # This is required to make sure that the git tag is created
      - name: Increment Version
        run: make release

      - name: Push Version Bump
        run: git push
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Build Package
        run: make build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
